export const AuthActionTypes = {
  CREATE_USER_START: " CREATE_USER_START",
  CREATE_USER_SUCCESS: " CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: " CREATE_USER_FAIL",

  LOGIN_USER_START: " LOGIN_USER_START",
  LOGIN_USER_SUCCESS: " LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: " LOGIN_USER_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",
};
export const ProductActionTypes = {
  CREATE_PRODUCT_START: " CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS: " CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: " CREATE_PRODUCT_FAIL",

  GET_PRODUCTS_START: " GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: " GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: " GET_PRODUCTS_FAIL",
};
