export const AuthActionTypes = {
  CREATE_USER_START: " CREATE_USER_START",
  CREATE_USER_SUCCESS: " CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: " CREATE_USER_FAIL",

  LOGIN_USER_START: " LOGIN_USER_START",
  LOGIN_USER_SUCCESS: " LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: " LOGIN_USER_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",
};
export const DashboardActionTypes = {
  GET_DASHBOARD_DATA_START: " GET_DASHBOARD_DATA_START",
  GET_DASHBOARD_DATA_SUCCESS: " GET_DASHBOARD_DATA_SUCCESS",
  GET_DASHBOARD_DATA_FAIL: " GET_DASHBOARD_DATA_FAIL",
};
export const UsersActionTypes = {
  GET_USERS_DATA_START: " GET_USERS_DATA_START",
  GET_USERS_DATA_SUCCESS: " GET_USERS_DATA_SUCCESS",
  GET_USERS_DATA_FAIL: " GET_USERS_DATA_FAIL",
};
export const ProductsActionTypes = {
  GET_PRODUCTS_DATA_START: " GET_PRODUCTS_DATA_START",
  GET_PRODUCTS_DATA_SUCCESS: " GET_PRODUCTS_DATA_SUCCESS",
  GET_PRODUCTS_DATA_FAIL: " GET_PRODUCTS_DATA_FAIL",
};
